    public enum Status
    {
        Dummy = 0,
        InTransit = 1,
        Rejected = 2,
        AckPlace = 3,
        Expired = 4,
        InCancel = 5,
        AckCancel = 6,
        RejectCancel = 7,
        InModify = 8,
        AckModify = 9,
        RejectModify = 10,
        Fill = 11,
        Suspend = 12,
        FillCorrect = 13,
        FillCancel = 14,
        FillBust = 15,
        Activeat = 16,
        Disconnect = 17,
        SyntheticActivated = 18,
        Update = 19,
        SyntheticFailed = 20,
        SyntheticOverfill = 21,
        SyntheticHang = 22
    }
