    public enum ChartPattern
    {
        BearishBeltHold = 0,
        BearishEngulfing = 1,
        BearishHarami = 2,
        BearishHaramiCross = 3,
        BullishBeltHold = 4,
        BullishEngulfing = 5,
        BullishHarami = 6,
        BullishHaramiCross = 7,
        DarkCloudCover = 8,
        Doji = 9,
        DownsideTasukiGap = 10,
        EveningStar = 11,
        FallingThreeMethods = 12,
        Hammer = 13,
        HangingMan = 14,
        InvertedHammer = 15,
        MorningStar = 16,
        PiercingLine = 17,
        RisingThreeMethods = 18,
        ShootingStar = 19,
        StickSandwich = 20,
        ThreeBlackCrows = 21,
        ThreeWhiteSoldiers = 22,
        UpsideGapTwoCrows = 23,
        UpsideTasukiGap = 24
    }
